travis:
  secure:
    BINSTAR_TOKEN: KgqJtUbKrCa7bD8+qaRaWFndZs146UgtWZRJuxkWDXfiB4WSKzTxuIrRyewlDQJoUINVcGsB6dclpLZBDZMEf6aIwu6P92n0z7pP+SQaITIZUmEC+OvVZqXNXA4TbvbzRiVBNYnt0VmQSa8T6stmrjl7Qy1G856D+6HVNuzSE2QdC0G30SceLAd8oKfS/W3GFI//SDdU5j3eP5c3SBOyPDQnI4Oa0q7UHlr3CJwIEgZQ1PTsMOtu97cRNezqsyI9+5BFWxe4RKjc44bBfjmt5A9SERG0T8Kgzsj4cJgxR3NtsWjse44mPf7ltzZ1+jsDO5OlJVjvGyQKM+0ie3j5xWH3eYfJovoiS5oBqOAO715qI7D7w4hVwfsFSK2ARR9R13C0f2AYWqa9pnyEwwhC73ncfltzreNKk+JWX9QS60yDejqzJ83AShg6HVXlfqi/7BqwHqpmY9iZdwz8MoHgZmAeXg+J4A+Q2RUpmghB55BHMUthzEeMPOlJ2iKr1ppnwqDvanRyul9CxBV8NFvnOhpECP3osAm2PWxICHhvcSGxPUT6eyUlRn9olLbIwOgtbg3zQpnDEIpPFdBPUDZnTiXHQ9ZVG6WmTnQ4iwVfEGaXRjSbtBehFQz1mrnvUxlg5FiIKgtAUoLr6bupvnyhxZorVTRViMtI5SlOhCNwcI0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
